"""Initial migration

Revision ID: 654a32ba179f
Revises: 
Create Date: 2023-12-08 22:20:02.929500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654a32ba179f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
